Repository CSE2024-team2/Invaders, pull requests merged in 2021-11, with the labels that each got.

#14 feat : Add a function to return to the list
  .github/PULL_REQUEST_TEMPLATE.md
  src/engine/Core.java
  src/engine/DrawManager.java
  src/screen/GameScreen.java
  src/screen/PauseScreen.java
Labels: documentation

#15 fix : Fix bug due to go to menu function
  src/engine/Core.java
  src/engine/DrawManager.java
  src/screen/GameScreen.java
  src/screen/PauseScreen.java
Labels: bug

#16 feat: Add restart function
  src/engine/DrawManager.java
  src/screen/GameScreen.java
  src/screen/PauseScreen.java
Labels: enhancement

#17 fix : Fix showing game over screen
  src/engine/Core.java
  src/screen/GameScreen.java
Labels: bug

#18 feat : add reward bullet
  res/graphics
  src/engine/DrawManager.java
  src/entity/RewardBullet.java
  src/screen/GameScreen.java
Labels: enhancement

#20 fix : increase pause delay
  src/screen/GameScreen.java
Labels: bug

#24 feat : Add background image
  .github/PULL_REQUEST_TEMPLATE.md
  res/moon.png
  src/engine/DrawManager.java
Labels: enhancement

#29 feat : Add Boss Sprite into spritemap
  res/graphics
  src/engine/DrawManager.java
  src/engine/MusicManager.java
Labels: enhancement
